<script lang="ts">
import { onDestroy } from 'svelte';
import { LatestRead, type ReadState } from '../vocabulary/state.ts';
import ReadStatus from '../components/ReadStatus.svelte';
import { productService } from './service.ts';
import { dateText, type Statistics } from './types.ts';
let range = $state<7 | 30>(7);
let view = $state<ReadState<Statistics>>({ status: 'loading', data: null });
const read = new LatestRead<Statistics>(v => { view = v; });
const load = () => read.run(() => productService.statistics(range));
$effect(() => { void load(); });
onDestroy(() => read.dispose());
const maximum = $derived(Math.max(1, ...(view.data?.dailyActivity ?? []).map(d => d.totalCount)));
</script>
<header><div><h1 tabindex="-1">学习统计</h1><p class="muted">来自已保存的正式复习与拼写记录。</p></div><label>时间范围<select bind:value={range}><option value={7}>最近 7 天</option><option value={30}>最近 30 天</option></select></label></header>
<div class="scroll"><ReadStatus status={view.status} errorMessage="无法读取学习统计，请重试。" retry={()=>{void load();}} />
 {#if view.status==='ready'&&view.data}{@const data=view.data}<div class="metrics">{#each [['今日新词',data.todayNewWordCount],['今日复习',data.todayReviewCount],['累计学习词数',data.totalLearnedWordCount],['累计复习次数',data.totalReviewCount],['连续学习天数',data.currentStreakDays]] as [title,value]}<p><strong>{value}</strong><span>{title}</span></p>{/each}</div>
 <section><h2>最近 {range} 天</h2><div class="metrics compact">{#each [['正式复习',data.periodFormalReviewCount],['首次学习词数',data.periodNewlyLearnedWordCount],['手动熟练',data.periodManualMasteryCount],['自动熟练',data.periodAutomaticMasteryCount]] as [title,value]}<p><strong>{value}</strong><span>{title}</span></p>{/each}<p><strong>{data.spellingEligible?`${Math.round(data.spellingPassed/data.spellingEligible*100)}%`:'—'}</strong><span>拼写首次正确率（{data.spellingPassed}/{data.spellingEligible}）</span></p></div><p class="muted">拼写仅统计已保存方向诊断的非熟练词；假名与表记分别计题。</p></section>
 <section><h2>每日活动</h2><figure><figcaption class="muted">本地时区：{data.timezone} · 正式复习次数</figcaption><div class="bars" style:grid-template-columns={`repeat(${data.dailyActivity.length},minmax(0,1fr))`} aria-hidden="true">{#each data.dailyActivity as day}<div title={`${dateText(day.day)}：${day.totalCount} 次`}><span style:height={`${day.totalCount/maximum*100}%`}></span></div>{/each}</div></figure><details><summary>查看逐日数据</summary><table><thead><tr><th>日期</th><th>总次数</th><th>新词</th><th>复习</th></tr></thead><tbody>{#each data.dailyActivity as day}<tr><th scope="row">{dateText(day.day)}</th><td>{day.totalCount}</td><td>{day.newWordCount}</td><td>{day.reviewCount}</td></tr>{/each}</tbody></table></details></section>
 <section><h2>评分分布</h2><div class="distribution">{#each ['忘记','模糊','认识','熟练'] as label,index}<p><span>{label}</span><strong>{data.ratingDistribution[index]}</strong></p>{/each}</div></section>
 <section><h2>容易遗忘的单词</h2><p class="muted">全历史中，复习或重新学习时评价「忘记」的次数。</p>{#if !data.topLapsedWords.length}<p role="status">暂无遗忘记录。</p>{:else}<ol>{#each data.topLapsedWords as word}<li><span lang="ja">{word.expression}（{word.reading}）</span><span>{word.meaningChinese}</span><strong>{word.lapseCount} 次</strong></li>{/each}</ol>{/if}</section>{#if !data.totalReviewCount}<p role="status" class="muted">开始学习后，这里将显示真实的学习记录。</p>{/if}{/if}
</div>
<style>header{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:20px;}header p{font-size:13px;margin-top:5px;}label{display:flex;flex-direction:column;gap:4px;white-space:nowrap;font-size:12px;}select{font:inherit;background:var(--surface);color:var(--text-primary);padding:8px;border:1px solid var(--border);border-radius:6px;}.scroll{min-height:0;flex:1;overflow:auto;padding:4px;}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:10px;margin-bottom:18px;}.metrics p{display:flex;flex-direction:column;gap:4px;padding:14px;background:var(--surface);border:1px solid var(--border);border-radius:8px;}.metrics strong{font-size:26px;}.metrics span{font-size:12px;color:var(--text-secondary);}.compact{margin:12px 0;}.compact strong{font-size:23px;}section{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:18px;margin-bottom:16px;}section>p{font-size:12px;margin:7px 0;}section h2{font-size:17px;}.bars{display:grid;gap:3px;height:120px;margin:18px 0;align-items:end;}.bars div{height:100%;display:flex;align-items:end;background:var(--surface-secondary);}.bars span{width:100%;background:var(--accent);border-radius:3px;}figure{margin:14px 0;}figcaption{font-size:12px;}summary{cursor:pointer;color:var(--accent);}table{width:100%;border-collapse:collapse;margin-top:10px;font-size:12px;}th,td{text-align:left;padding:6px;border-bottom:1px solid var(--border);}.distribution{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:14px;}.distribution p{display:flex;flex-direction:column;gap:5px;}.distribution strong{font-size:22px;}ol{padding-left:20px;}li{padding:8px 0;border-bottom:1px solid var(--border);display:flex;flex-wrap:wrap;gap:6px 12px;overflow-wrap:anywhere;}li strong{margin-left:auto;}</style>
