import {test} from 'node:test';import assert from 'node:assert/strict';
import {FileActions,SettingsController,confirmedAction} from '../src/lib/product/actions.ts';
import {defaultFilters} from '../src/lib/product/types.ts';import {LatestRead,WordBrowser} from '../src/lib/vocabulary/state.ts';
import {kanaGroups,kanaMove} from '../src/lib/product/kana.ts';import {dispatchKey,dispatchPageKey,isSafeReferenceKey,CompositionGuard,shortcutReference} from '../src/lib/study/keyboard.ts';
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
const key=(key,extra={})=>({key,repeat:false,isComposing:false,ctrlKey:false,metaKey:false,altKey:false,shiftKey:false,...extra});
const preview=(kind='csv')=>({kind,token:'opaque-token',validRows:1,errorCount:0});
const summary={csv:{imported:1,updated:0,skipped:0,errors:0},backup:null};
function files(overrides={}){let calls=[];const service={pickImport:async(k,t)=>{calls.push(['pick',k,t]);return preview(k);},confirmImport:async(...args)=>{calls.push(['confirm',...args]);return summary;},cancelImport:async()=>{calls.push(['cancel']);},exportFile:async(...args)=>{calls.push(['export',...args]);return 'Kotoba.csv';},...overrides};let last;const c=new FileActions(service,s=>{last=s;});return {c,calls,view:()=>last};}
test('file picker cancellation yields no confirmation or mutation',async()=>{const h=files({pickImport:async()=>null});await h.c.pick('csv',{bookId:'book',newBookName:null});await h.c.confirm(true,'update','overwrite');assert.equal(h.c.state.preview,null);assert.equal(h.calls.length,0);});
test('CSV confirmation is explicit and sends only staged token and duplicate policy',async()=>{const h=files();await h.c.pick('csv',{bookId:'book',newBookName:null});await h.c.confirm(false,'update','merge');assert.equal(h.calls.length,1);await h.c.confirm(true,'update','merge');await h.c.confirm(true,'update','merge');assert.deepEqual(h.calls[1],['confirm','opaque-token','update',null]);assert.equal(h.calls.length,2);assert.equal(h.view().summary.csv.imported,1);});
test('backup cancel discards preview without restoring; overwrite requires explicit confirmation',async()=>{const h=files();await h.c.pick('backup',null);await h.c.cancel();assert.equal(h.c.state.preview,null);assert.deepEqual(h.calls.map(c=>c[0]),['pick','cancel']);await h.c.pick('backup',null);await h.c.confirm(true,'skip','overwrite');assert.deepEqual(h.calls.at(-1),['confirm','opaque-token',null,'overwrite']);});
test('failed restore preserves staged preview for retry and does not expose paths',async()=>{let attempts=0;const h=files({confirmImport:async()=>{if(++attempts===1)throw new Error('/private/user/sqlite');return summary;}});await h.c.pick('backup',null);await h.c.confirm(true,'skip','merge');assert.equal(h.c.state.preview.token,'opaque-token');assert.ok(!h.c.state.error.includes('/private'));assert.equal(h.c.state.summary,null);await h.c.confirm(true,'skip','merge');assert.equal(h.c.state.preview,null);assert.equal(attempts,2);});
test('pending native file action blocks duplicate pick/export/confirm',async()=>{const wait=deferred();const h=files({pickImport:()=>wait.promise});const pending=h.c.pick('csv',{bookId:'book',newBookName:null});assert.equal(h.view().pending,true);await h.c.pick('backup',null);await h.c.export('backup',null);await h.c.confirm(true,'skip','merge');assert.equal(h.calls.length,0);wait.resolve(preview());await pending;assert.equal(h.view().pending,false);});
test('export cancellation is distinct from a successful exported file',async()=>{const h=files({exportFile:async()=>null});await h.c.export('backup',null);assert.equal(h.view().exported,null);assert.equal(h.view().error,null);});
const settings={formatVersion:1,dailyNewWordCount:10,dailyReviewWordCount:20,randomizesStudyOrder:true,selectedBookId:'book'};
test('settings save waits for authoritative persistence, clamps from returned value and restarts',async()=>{let stored={...settings};const wait=deferred();let count=0;const service={settings:async()=>({...stored}),saveSettings:async value=>{count++;await wait.promise;stored={...value,dailyNewWordCount:100};return {...stored};}};let last;const c=new SettingsController(service,s=>{last=s;});await c.load();const pending=c.save({...settings,dailyNewWordCount:999,randomizesStudyOrder:false});assert.equal(last.pending,true);assert.equal(last.saved,false);await c.save(settings);assert.equal(count,1);wait.resolve();await pending;assert.equal(last.value.dailyNewWordCount,100);assert.equal(last.saved,true);const restarted=new SettingsController(service,()=>{});await restarted.load();assert.equal(restarted.state.value.randomizesStudyOrder,false);});
test('failed settings save retains authoritative value and does not falsely report saved',async()=>{const c=new SettingsController({settings:async()=>settings,saveSettings:async()=>{throw new Error('absolute secret');}},()=>{});await c.load();await c.save({...settings,randomizesStudyOrder:false});assert.equal(c.state.value.randomizesStudyOrder,true);assert.equal(c.state.saved,false);assert.ok(!c.state.error.includes('secret'));});
test('confirmed reset cancel makes no mutation; confirmation calls exactly once',async()=>{let count=0;const work=async()=>{count++;};assert.equal(await confirmedAction(false,work),false);assert.equal(count,0);assert.equal(await confirmedAction(true,work),true);assert.equal(count,1);});
test('filter plus sort state resets pagination while preserving search/book/tags',async()=>{let filters={...defaultFilters('book'),search:'shin',status:'difficult',sort:'lapseCount',tag:'复合'};const calls=[];let page;const c=new WordBrowser('book',async(search,_book,offset)=>{calls.push({...filters,search,offset});return {items:[],total:0,limit:50,offset};},s=>{page=s;});c.query='shin';await c.page(100);filters={...filters,status:'mastered',sort:'nextDue'};await c.page(0);assert.deepEqual(calls.at(-1),{...filters,offset:0});assert.equal(page.status,'ready');c.dispose();});
test('history latest read ignores late response after another word opens',async()=>{const old=deferred();let view;const read=new LatestRead(s=>{view=s;});const first=read.run(()=>old.promise);await read.run(async()=>({items:[{transition:'复习 → 重新学习'}],total:1}));old.resolve({items:[{transition:'old'}],total:100});await first;assert.equal(view.data.total,1);});
test('forecast loading failure and recovery retain explicit empty/ready distinction',async()=>{let view;const read=new LatestRead(s=>{view=s;});await read.run(async()=>{throw Error('db path');});assert.equal(view.status,'error');await read.run(async()=>Array.from({length:7},(_,i)=>({day:i,count:0})));assert.equal(view.status,'ready');assert.equal(view.data.length,7);assert.ok(view.data.every(d=>d.count===0));});
test('statistics switching 7 to 30 days never publishes stale range',async()=>{const seven=deferred();let view;const read=new LatestRead(s=>{view=s;});const pending=read.run(()=>seven.promise);await read.run(async()=>({days:30,dailyActivity:Array(30).fill({totalCount:0})}));seven.resolve({days:7,dailyActivity:[]});await pending;assert.equal(view.data.days,30);assert.equal(view.data.dailyActivity.length,30);});
test('kana static reference matches complete Mac groups and historical labels',()=>{assert.deepEqual(kanaGroups.map(g=>g.rows.flatMap(r=>r.entries).filter(Boolean).length),[48,25,33]);const all=kanaGroups.flatMap(g=>g.rows.flatMap(r=>r.entries).filter(Boolean));assert.equal(new Set(all.map(e=>e.hiragana)).size,106);assert.equal(new Set(all.map(e=>e.katakana)).size,106);assert.ok(all.every(e=>e.romaji.length));assert.deepEqual(all.filter(e=>e.historical).map(e=>e.romaji),['wi','we']);assert.equal(all.find(e=>e.hiragana==='を').romaji,'wo');});
test('kana arrow navigation skips absent cells and remains bounded',()=>{const group=kanaGroups[0];assert.equal(kanaMove(group,35,'ArrowRight'),37);assert.equal(kanaMove(group,35,'ArrowDown'),40);assert.equal(kanaMove(group,0,'ArrowLeft'),0);assert.equal(kanaMove(group,50,'ArrowDown'),50);assert.equal(isSafeReferenceKey(key('ArrowRight',{isComposing:true})),false);});
test('help and card paging share IME/repeat/pending/modal/editing guards',()=>{const c={phase:'flashcard',editing:false,spellingInput:false,composing:false,dialog:false,pending:false,revealed:true,platform:'windows',hasSecondaryPage:true};assert.deepEqual(dispatchKey(key('ArrowRight'),c),{kind:'pageNext'});assert.deepEqual(dispatchKey(key('?',{shiftKey:true}),c),{kind:'help'});for(const guard of [{composing:true},{pending:true},{dialog:true},{editing:true},{revealed:false}])assert.equal(dispatchKey(key('ArrowRight'),{...c,...guard}),null);for(const value of ['?','ArrowLeft','ArrowRight'])for(const e of [{repeat:true},{isComposing:true},{keyCode:229}])assert.equal(dispatchKey(key(value,e),c),null);const ime=new CompositionGuard();const turn=[];ime.start();ime.end(fn=>turn.push(fn));assert.equal(dispatchPageKey(key('?'),{...c,composing:ime.active}),null);turn[0]();assert.equal(dispatchPageKey(key('?'),{...c,composing:ime.active}),'help');assert.equal(dispatchPageKey(key('?'),{...c,editing:true}),null);assert.equal(shortcutReference('windows').find(s=>s.title==='通用').items[0][1],'?');});
