import {test} from "node:test";
import assert from "node:assert/strict";
import {StudySessionController} from "../src/lib/study/controller.ts";
import {SpellingSession,questions,containsHan,answerCorrect,normalizeText,normalizeReading} from "../src/lib/study/spelling.ts";
import {CompositionGuard,dispatchKey,shortcutReference} from "../src/lib/study/keyboard.ts";
const card=(id="a",expression="食べる",reading="たべる",meaning="吃")=>({word:{id,expression,reading,meaningChinese:meaning,bookId:"book",bookName:"N5",jlptLevel:"N5",learningStatus:"unlearned",partOfSpeech:"动词",exampleJapanese:`朝ご飯を${expression}。`,exampleChinese:"吃早饭。",tags:[],loanword:null},kind:"newWord",expectedProgress:null,isFavorite:false});
const progress=(id,state="review")=>({id:`p-${id}`,wordId:id,state,dueAt:200,intervalDays:2,reviewCount:1,lapseCount:0,lastReviewedAt:100,createdAt:100,updatedAt:100});
const commit=(r,state=r.rating==="easy"?"suspended":"review",auto=false)=>({progress:progress(r.wordId,state),logId:`l-${r.wordId}`,automaticMastery:auto,didLapse:false});
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
function harness(cards=[card()],overrides={}){const calls={formal:[],reinforcement:[],favorite:[],enrich:[]};const service={availability:async()=>({}),start:async()=>({cards:structuredClone(cards),timezone:"Test/Calendar"}),formal:async r=>{calls.formal.push(structuredClone(r));return commit(r);},reinforcementMastered:async(id,p,now)=>{calls.reinforcement.push({id,p,now});return {...p,state:"suspended",intervalDays:0,dueAt:now};},favorite:async(id,expected)=>{calls.favorite.push({id,expected});return !expected;},enrich:async entries=>{calls.enrich.push(structuredClone(entries));},...overrides};let finished=0;let now=100;const controller=new StudySessionController(service,()=>{},()=>now,q=>q,()=>{finished++;});return {c:controller,calls,service,setNow:n=>{now=n;},finished:()=>finished,start:()=>controller.start("book","mixed")};}
async function cleanSpelling(c){let steps=0;while(["spellingExpression","spellingReading"].includes(c.phase)){assert.ok(++steps<100);if(!c.spelling.locked)c.input(c.spelling.current.expected);await c.spellingEnter();}}
test("formal ratings require reveal and only advance after successful commit",async()=>{const wait=deferred();let count=0;const h=harness([card(),card("b")],{formal:r=>{count++;return wait.promise;}});await h.start();await h.c.rateFormal("good");assert.equal(count,0);h.c.reveal();const pending=h.c.rateFormal("good");assert.equal(h.c.pending,true);assert.equal(h.c.index,0);assert.equal(h.c.outcomes.size,0);await h.c.rateFormal("hard");await h.c.toggleFavorite();h.c.requestExit();assert.equal(count,1);assert.equal(h.c.exitDialog,false);wait.resolve(commit({wordId:"a",rating:"good"}));await pending;assert.equal(h.c.index,1);assert.equal(h.c.revealed,false);assert.equal(h.c.outcomes.size,1);});
test("formal failure retains card, rating, original time and snapshot for retry",async()=>{let count=0;const requests=[];const h=harness([card()],{formal:async r=>{requests.push(structuredClone(r));if(++count===1)throw {code:"save",message:"secret path"};return commit(r);}});await h.start();h.c.reveal();await h.c.rateFormal("hard");assert.equal(h.c.index,0);assert.equal(h.c.outcomes.size,0);assert.equal(h.c.card.expectedProgress,null);assert.equal(h.c.snapshot().error,"保存失败，请重试。");h.setNow(999);await h.c.rateFormal("easy");assert.equal(count,1);await h.c.retryRating();assert.deepEqual(requests[0],requests[1]);assert.equal(h.c.outcomes.get("a").rating,"hard");});
test("stale snapshot invalidates safely and cannot overwrite current progress",async()=>{const h=harness([card()],{formal:async()=>{throw {code:"stale"};}});await h.start();h.c.reveal();await h.c.rateFormal("good");assert.equal(h.c.phase,"error");assert.equal(h.c.index,0);assert.equal(h.c.outcomes.size,0);assert.match(h.c.error,/学习状态已发生变化/);await h.c.retryRating();await h.c.rateFormal("easy");assert.equal(h.c.card.expectedProgress,null);});
test("timezone resolution failure blocks session and has no UTC fallback",async()=>{const h=harness([],{start:async()=>{throw {code:"timezone"};}});await h.start();assert.equal(h.c.phase,"error");assert.match(h.c.error,/系统时区/);assert.equal(h.c.timezone,"");assert.equal(h.calls.formal.length,0);});
test("empty before start remains distinct from completed summary",async()=>{const h=harness([]);await h.start();assert.equal(h.c.phase,"emptyQueue");assert.equal(h.c.snapshot().summary,null);h.c.finishOnce();assert.equal(h.finished(),0);});
test("Again reinforcement is session-only; Hard and Good finish without formal mutations",async()=>{for(const rating of ["hard","good"]){const h=harness();await h.start();h.c.reveal();await h.c.rateFormal("again");assert.equal(h.c.phase,"flashcardRetry");const stored=structuredClone(h.c.card.expectedProgress);h.c.reveal();await h.c.rateReinforcement("again");assert.deepEqual(h.c.card.expectedProgress,stored);h.c.reveal();await h.c.rateReinforcement(rating);assert.equal(h.c.phase,"spellingExpression");assert.equal(h.calls.formal.length,1);assert.equal(h.calls.reinforcement.length,0);assert.equal(h.c.outcomes.get("a").retryCount,2);assert.equal(h.c.outcomes.get("a").rating,"again");}});
test("reinforcement Mastered failure preserves candidates; retry commits once",async()=>{let attempts=0;const h=harness([],{start:async()=>({cards:[card()],timezone:"Test"}),reinforcementMastered:async(id,p,now)=>{if(++attempts===1)throw {code:"save"};return {...p,state:"suspended",intervalDays:0,dueAt:now};}});await h.start();h.c.reveal();await h.c.rateFormal("again");h.c.reveal();const before=h.c.index;await h.c.rateReinforcement("easy");assert.equal(h.c.index,before);assert.equal(h.c.outcomes.get("a").mastered,false);assert.equal(h.c.card.expectedProgress.state,"review");await h.c.retryRating();assert.equal(h.c.phase,"summary");assert.equal(h.c.snapshot().summary.mastered,1);assert.equal(h.c.outcomes.get("a").rating,"again");assert.equal(h.calls.formal.length,1);assert.equal(h.c.spelling.expression.length,0);});
test("formal manual and automatic mastery exclude all spelling and reinforcement candidates",async()=>{for(const rating of ["easy","good"]){const h=harness([card()],{formal:async r=>commit(r,"suspended",rating==="good")});await h.start();h.c.reveal();await h.c.rateFormal(rating);assert.equal(h.c.phase,"summary");assert.equal(h.c.spelling.expression.length,0);assert.equal(h.c.spelling.reading.length,0);assert.equal(h.c.outcomes.get("a").rating,rating);assert.equal(h.c.snapshot().summary.mastered,1);}});
test("formal and reinforcement entry points cannot substitute for each other",async()=>{const h=harness();await h.start();h.c.reveal();await h.c.rateReinforcement("good");assert.equal(h.c.index,0);await h.c.rateFormal("again");h.c.reveal();await h.c.rateFormal("good");assert.equal(h.calls.formal.length,1);assert.equal(h.c.phase,"flashcardRetry");});
test("favorite commits without advancing, and failure preserves UI/progress",async()=>{const h=harness();await h.start();const before=structuredClone(h.c.card);await h.c.toggleFavorite();assert.equal(h.c.card.isFavorite,true);assert.equal(h.c.index,0);assert.equal(h.calls.formal.length,0);assert.deepEqual(h.c.card.expectedProgress,before.expectedProgress);h.service.favorite=async()=>{throw {code:"save"};};await h.c.toggleFavorite();assert.equal(h.c.card.isFavorite,true);assert.match(h.c.error,/收藏/);});
test("round one includes kana words, masks all target occurrences and deduplicates",()=>{const kanji=card(),kana=card("b","ゆっくり","ゆっくり","慢慢地");const list=questions([kanji,kana,kanji],"meaningToExpression");assert.equal(list.length,2);assert.equal(list[0].prompt,"吃");assert.equal(list[0].context,"朝ご飯を＿＿＿＿。");assert.equal(list[1].expected,"ゆっくり");});
test("round two uses exact Han ranges including supplementary compatibility characters",()=>{for(const value of ["食べる","一人","\u{20000}","\u{2f800}","\u{31350}"])assert.equal(containsHan(value),true);for(const value of ["ゆっくり","コンピューター","Ａ","〇"])assert.equal(containsHan(value),false);assert.equal(questions([card(),card("b","テレビ","テレビ")],"expressionToReading").length,1);});
test("empty/invalid spelling prompts skip correctly to available round",()=>{assert.equal(new SpellingSession([card("a","確認","かくにん","")]).phase,"reading");assert.equal(new SpellingSession([card("a","かな","かな","")]).phase,"completed");const mastered=card();mastered.expectedProgress=progress("a","suspended");assert.equal(new SpellingSession([mastered]).phase,"completed");});
test("expression uses NFKC and spaces, reading only kana with exact comparison",()=>{assert.equal(normalizeText("　Ａ B　"),"AB");assert.equal(normalizeReading(" ｶﾞｸ ｾｲ "),"か\u3099くせい");assert.equal(answerCorrect("タベ ル","たべる","expressionToReading"),true);for(const value of ["taberu","食べる","たべます","たべる!","たべる\t"])assert.equal(answerCorrect(value,"たべる","expressionToReading"),value==="たべる\t");assert.equal(answerCorrect("ﾃﾚﾋﾞ","テレビ","meaningToExpression"),true);assert.equal(answerCorrect("てれび","テレビ","meaningToExpression"),false);});
test("hint is round-one only, irreversible for appearance, and forces clean retry",()=>{const s=new SpellingSession([card("a","かな","かな")]);assert.equal(s.revealHint(),true);assert.equal(s.revealHint(),false);s.answer="かな";assert.equal(s.enter(),"submitted");assert.equal(s.requeued,true);assert.equal(s.queue.length,2);s.enter();assert.equal(s.hint,false);s.answer="かな";s.enter();s.enter();assert.equal(s.phase,"completed");assert.deepEqual(s.roundSummary("expression"),{totalCount:1,firstAttemptCorrectCount:0,retryCorrectCount:1,usedHintCount:1});});
test("wrong stays current; correction appends only once; phases remain ordered",()=>{const s=new SpellingSession([card()]);for(const value of ["食べます","食べません"]){s.answer=value;s.enter();assert.equal(s.index,0);assert.equal(s.locked,false);}s.answer="食べる";s.enter();assert.equal(s.queue.length,2);assert.equal(s.results.get("a").expression.wrongCount,2);s.enter();s.answer="食べる";s.enter();s.enter();assert.equal(s.phase,"reading");assert.equal(s.revealHint(),false);s.answer="タベル";s.enter();s.enter();assert.equal(s.phase,"completed");assert.equal(s.roundSummary("expression").retryCorrectCount,1);assert.equal(s.roundSummary("reading").firstAttemptCorrectCount,1);assert.equal(s.results.get("a").lastTypedAnswer,"食べません");});
test("round-two wrong then correction requeues and requires a clean reading pass",()=>{const s=new SpellingSession([card("a","確認","かくにん","")]);s.answer="かくじん";s.enter();s.answer="カクニン";s.enter();assert.equal(s.requeued,true);s.enter();s.answer="かくにん";s.enter();s.enter();assert.equal(s.phase,"completed");assert.equal(s.roundSummary("reading").retryCorrectCount,1);assert.equal(s.results.get("a").reading.wrongCount,1);});
test("spelling composition never submits or advances either answering or locked state",()=>{const s=new SpellingSession([card()]);s.answer="食べる";assert.equal(s.enter(true),"ignored");assert.equal(s.locked,false);assert.equal(s.revealHint(true),false);s.enter();assert.equal(s.enter(true),"ignored");assert.equal(s.index,0);});
test("spelling enrichment failure preserves formal result and can retry unchanged entries",async()=>{let attempts=0;const entries=[];const h=harness([card("a","かな","かな")],{enrich:async value=>{entries.push(structuredClone(value));if(++attempts===1)throw {code:"save"};}});await h.start();h.c.reveal();await h.c.rateFormal("good");await cleanSpelling(h.c);assert.equal(h.c.phase,"error");assert.equal(h.calls.formal.length,1);assert.equal(h.c.outcomes.size,1);await h.c.retrySpelling();assert.equal(h.c.phase,"summary");assert.deepEqual(entries[0],entries[1]);assert.equal(h.calls.formal.length,1);});
test("continue after spelling save failure retains formal progress and summary metrics",async()=>{const h=harness([card("a","かな","かな")],{enrich:async()=>{throw {code:"save"};}});await h.start();h.c.reveal();await h.c.rateFormal("good");await cleanSpelling(h.c);h.c.continueWithoutSpellingSave();assert.equal(h.c.phase,"summary");assert.equal(h.c.snapshot().summary.expression.firstAttemptCorrectCount,1);assert.equal(h.calls.formal.length,1);});
test("summary button and repeated Return race invokes completion exactly once",async()=>{const h=harness();await h.start();h.c.reveal();await h.c.rateFormal("easy");h.c.finishOnce();h.c.finishOnce();h.c.finishOnce();assert.equal(h.finished(),1);assert.equal(h.c.phase,"completed");});
test("exit confirmation pauses actions, continue preserves card, exit retains committed DB calls",async()=>{const h=harness([card(),card("b")]);await h.start();h.c.reveal();await h.c.rateFormal("good");let left=0;h.c.requestExit(()=>left++);assert.equal(h.c.exitDialog,true);h.c.reveal();await h.c.rateFormal("easy");assert.equal(h.calls.formal.length,1);h.c.continueLearning();assert.equal(h.c.card.word.id,"b");h.c.requestExit(()=>left++);h.c.confirmExit();h.c.confirmExit();assert.equal(left,1);assert.equal(h.calls.formal.length,1);assert.equal(h.c.phase,"cancelled");});
const key=(value,extra={})=>({key:value,repeat:false,isComposing:false,ctrlKey:false,metaKey:false,altKey:false,shiftKey:false,...extra});
const context=(extra={})=>({phase:"flashcard",editing:false,spellingInput:false,composing:false,dialog:false,pending:false,revealed:true,platform:"windows",...extra});
test("keyboard central mappings distinguish formal/reinforcement and reveal gate",()=>{assert.deepEqual(dispatchKey(key("1"),context()),{kind:"formalRating",rating:"again"});assert.deepEqual(dispatchKey(key("3"),context({phase:"flashcardRetry"})),{kind:"reinforcementRating",rating:"good"});assert.equal(dispatchKey(key("1"),context({revealed:false})),null);assert.equal(dispatchKey(key("ArrowRight"),context()),null);assert.equal(dispatchKey(key(" "),context({revealed:false})).kind,"reveal");assert.equal(dispatchKey(key("f"),context()).kind,"favorite");});
test("keyboard repeat, modifiers, editing, dialog and pending block study actions",()=>{for(const value of ["1","2","3","Backspace","Delete"," ","f","Escape"]){for(const guard of [{repeat:true},{isComposing:true},{keyCode:229},{ctrlKey:true},{metaKey:true},{altKey:true},{shiftKey:true}])assert.equal(dispatchKey(key(value,guard),context()),null);for(const guard of [{editing:true},{dialog:true},{pending:true},{composing:true}])assert.equal(dispatchKey(key(value),context(guard)),null);}assert.equal(dispatchKey(key("Enter",{repeat:true}),context({phase:"summary"})),null);});
test("IME composing Enter/Escape/Delete/Space/numbers/F never dispatch in spelling",()=>{for(const value of ["Enter","Escape","Delete","Backspace"," ","1","2","3","f"]){assert.equal(dispatchKey(key(value,{isComposing:true}),context({phase:"spellingExpression",editing:true,spellingInput:true})),null);assert.equal(dispatchKey(key(value),context({phase:"spellingReading",composing:true,editing:true,spellingInput:true})),null);}});
test("platform hint modifier is exact, round-one only, search never steals spelling input",()=>{assert.equal(dispatchKey(key("H",{ctrlKey:true,shiftKey:true}),context({phase:"spellingExpression",editing:true,spellingInput:true})).kind,"hint");assert.equal(dispatchKey(key("H",{metaKey:true,shiftKey:true}),context({phase:"spellingExpression",platform:"mac"})).kind,"hint");assert.equal(dispatchKey(key("H",{ctrlKey:true,shiftKey:true}),context({phase:"spellingReading"})),null);assert.equal(dispatchKey(key("f",{ctrlKey:true}),context({phase:"spellingExpression",editing:true,spellingInput:true})),null);assert.equal(dispatchKey(key("f",{ctrlKey:true}),context({phase:"idle"})).kind,"search");assert.equal(dispatchKey(key("Enter"),context({phase:"spellingExpression",editing:true,spellingInput:true})).kind,"spellingEnter");});
test("compositionend does not submit; trailing IME commit key is blocked until event turn ends",()=>{const guard=new CompositionGuard();const pending=[];guard.start();guard.end(fn=>pending.push(fn));assert.equal(guard.active,true);assert.equal(dispatchKey(key("Enter"),context({phase:"spellingExpression",composing:guard.active})),null);pending[0]();assert.equal(guard.active,false);assert.equal(dispatchKey(key("Enter"),context({phase:"spellingExpression",composing:guard.active})).kind,"spellingEnter");});
test("shortcut reference is one source and only lists implemented card actions",()=>{for(const platform of ["mac","windows"]){const reference=shortcutReference(platform);assert.equal(reference.find(s=>s.title==="拼写").items[1][1],platform==="mac"?"⌘+Shift+H":"Ctrl+Shift+H");assert.ok(!JSON.stringify(reference).includes("切换卡片页"));}});
test("full memory session has one formal per word and enrichment targets original logs",async()=>{const h=harness([card("a"),card("b","かな","かな"),card("c")],{formal:async r=>{h.calls.formal.push(structuredClone(r));return commit(r,r.wordId==="c"?"suspended":"review",r.wordId==="c");}});await h.start();h.c.reveal();await h.c.rateFormal("again");h.c.reveal();await h.c.rateFormal("hard");h.c.reveal();await h.c.rateFormal("good");assert.equal(h.c.phase,"flashcardRetry");h.c.reveal();await h.c.rateReinforcement("good");h.c.hint();h.c.input("wrong");await h.c.spellingEnter();await cleanSpelling(h.c);const summary=h.c.snapshot().summary;assert.equal(summary.total,3);assert.equal(summary.mastered,1);assert.equal(summary.forgotten,1);assert.equal(summary.fuzzy,1);assert.equal(summary.expression.totalCount,2);assert.equal(summary.reading.totalCount,1);assert.equal(h.calls.formal.length,3);assert.equal(h.calls.enrich.length,1);assert.deepEqual(h.calls.enrich[0].map(e=>e.logId).sort(),["l-a","l-b"]);assert.equal(h.calls.enrich[0].find(e=>e.wordId==="a").spellingWrongCount,1);h.c.finishOnce();assert.equal(h.finished(),1);});
test("normalization matches 60 vectors produced by actual Mac AnswerChecker source",async()=>{
 const {readFile}=await import("node:fs/promises");
 const vectors=JSON.parse(await readFile(new URL("./fixtures/mac-spelling-golden.json",import.meta.url),"utf8"));
 assert.equal(vectors.length,60);
 for(const v of vectors){const normalize=v.direction==="meaningToExpression"?normalizeText:normalizeReading;
  assert.equal(normalize(v.answer),v.normalizedAnswer,JSON.stringify(v));
  assert.equal(normalize(v.expected),v.normalizedExpected,JSON.stringify(v));
  assert.equal(answerCorrect(v.answer,v.expected,v.direction),v.correct,JSON.stringify(v));
 }
});
